auto: true
server: true
baseurl:
permalink: /:title

# Prose testing stuff
prose:
  siteurl: http://thatsok.github.com/bootstrap
  media: 'media'
  metadata:
    _posts/articles:
      - name: "layout"
        field:
          element: "hidden"
          value: "article"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "text"
          label: "Date: YYYY-MM-DD HH:MM"
          value: CURRENT_DATETIME
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: 'http://bret.io/pages/tags.jsonp'
          alterable: true
    _posts/notes:
      - name: "layout"
        field:
          element: "hidden"
          value: "note"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "text"
          label: "Date: YYYY-MM-DD HH:MM"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: 'http://bret.io/pages/tags.jsonp'
          alterable: true
      - name: "reply_url"
        field:
          element: "text"
          label: "Reply to URL"
      - name: "reply_title"
        field:
          element: "text"
          label: "Name of reply"
    _posts/linklog:
      - name: "layout"
        field:
          element: "hidden"
          value: "linklog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "text"
          label: "Date: YYYY-MM-DD HH:MM"
          value: CURRENT_DATETIME
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: 'http://bret.io/pages/tags.jsonp'
          alterable: true
      - name: "external_url"
        field:
            element: "text"
            label: "Link"
